name: grf_env
channels:
  - conda-forge  # for compatibility with some scientific packages

dependencies:
  - python=3.10
  - pip=25.1.1
  - setuptools
  - wheel
  - numpy
  - psutil
  - pygame
  - pip:
      - absl-py==2.3.1
      - six
      - moviepy
      - jinja2==3.1.6
      - loguru==0.7.3
      - networkx==3.4.2
      - opencv-python==4.12.0.88
      - protobuf==6.31.1
      - grpcio==1.73.1
      - pre-commit==4.2.0
      - scipy==1.15.3
      - tensorboard==2.19.0
      - tqdm==4.67.1
      - virtualenv==20.31.2
      - wandb==0.21.0
      - torch==2.7.1
      - torchrl==0.9.1
      - pettingzoo==1.25.0
      - gymnasium==1.2.0
      - git+https://github.com/xihuai18/Common-Multi-agent-Environments.git
      - git+https://github.com/xihuai18/GFootball-Gymnasium-Pettingzoo.git